version: '3.9'

services:
  mysql_db:
    image: mysql:8.3.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "9896:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app_sale:
    image: viktorch701/sale_app:1.0.1
    container_name: app_sale
    restart: always
    ports:
      - "9898:9898"
    environment:
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mysql_db

volumes:
  mysql_data: